version: "3"

# docker run --rm --name courses-database -v courses-data:/var/lib/postgresql/data -p 5432:5432
# -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=courses-db -d postgres:13-alpine
# psql -h localhost -p 5433 -d cars-db  -U admin
services:
  cars-database:
    image: "postgres:13-alpine"
    ports:
      - "5433:5432"
    volumes:
      - "cars-db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=cars-db"
volumes:
  cars-db-data: